### Subset data

```{r subset_data}
# Drop rows for individuals with missing data
cat(sprintf('- Dropping %d / %d rows from shelter dataset (not shared)\n', 
            sum(!shelters$mci %in% ids_to_use),
            nrow(shelters)))
shelters_subset <- shelters[shelters$mci %in% ids_to_use,]

cat(sprintf('- Dropping %d / %d rows from behavior dataset (not shared)\n', 
            sum(!bhs$mci %in% ids_to_use),
            nrow(bhs)))
bhs_subset <- bhs[bhs$mci %in% ids_to_use,]

cat(sprintf('- Dropping %d / %d rows from CYF dataset (not shared)\n', 
            sum(!cyf$mci %in% ids_to_use),
            nrow(cyf)))
cyf_subset <- cyf[cyf$mci %in% ids_to_use,]
```

### Visualization

```{r}
# Behavior and health services
bhs_collapsed <- bhs_subset %>%
    group_by(mci) %>%
    summarize(bhs_num_visits=n(),
              bhs_num_unique_providers=n_distinct(PRVDR_NAME))
              #county_tot=sum(CNTY_TOT),
              #total_units=sum(TOT_UNITS))

# drop INVLV and birthdate columns and keep a single row for each individual
# TODO: add duration in CYF?
cyf_collapsed <- cyf_subset %>% 
    group_by(mci) %>%
    mutate(cyf_num_welfare=n()) %>%
    select(-CAS_ID, -CL_ID, -BRTH_DT, -starts_with('INVLV'))
cyf_collapsed <- cyf_collapsed[!duplicated(cyf_collapsed$mci),]

# Shelters
#min_stay=min(DURATION_OF_STAY),
#max_stay=max(DURATION_OF_STAY),
shelters_collapsed <- shelters_subset %>%
    group_by(mci) %>%
    summarize(shelter_num_stays=n(),
              shelter_num_unique_hud_types=n_distinct(HUD_PROJECT_TYPE),
              shelter_avg_stay=median(DURATION_OF_STAY))

# Combined dataset
dataset_list <- lapply(paste0(datasets, '_collapsed'), get)
names(dataset_list) <- datasets

dat <- Reduce(function(x, y) merge(x, y, by='mci'), dataset_list)

# Drop any rows with NA's (should be small)
cat(sprintf('- Removing %d incomplete rows...\n', sum(!complete.cases(dat))))
dat <- dat[complete.cases(dat),]

# Remove entries with values outside of the expected range
if ('shelters' %in% datasets) {
    dat <- dat %>% filter(shelter_avg_stay < 5000)
}
if ('bhs' %in% datasets) {
    dat <- dat %>% filter(bhs_num_visits < 1000)
}
if ('cyf' %in% datasets) {
    dat <- dat %>% filter(AGE < 75)
}

# version of data with only numeric variables, and without the ID column
mat <- as.matrix(dat[,!colnames(dat) %in% c('mci', 'RACE', 'GENDER')])

# Normalize columns
mat <- scale(mat)
```

Variable correlation heatmap

```{r, variable_heatmap}
# spearman correlation matrix
cor_mat <- cor(mat, method='spearman')
heatmap.2(cor_mat, trace='none', col=viridis, cellnote=round(cor_mat, 3), margin=c(16,16))
```

Individual correlation heatmap

```{r, individual_heatmap, warning=FALSE}
# drop any constant rows
zero_var <- apply(mat, 1, var) == 0
mat <- mat[!zero_var,]
dat <- dat[!zero_var,]

# individual heatmap (subsample if > 1000)
if (nrow(mat) > 1000) {
    ind <- sample(1:nrow(mat), 1000)
    cor_mat <- cor(t(mat[ind,]), method='spearman')
} else {
    cor_mat <- cor(t(mat), method='spearman')
}
heatmap.2(cor_mat, trace='none', col=viridis)
```

PCA of individuals

```{r, individual_pca}
prcomp_results <- prcomp(mat)
var_explained <- round(summary(prcomp_results)$importance[2,] * 100, 2)

xl <- sprintf("PC1 (%.2f%% variance)", var_explained[1])
yl <- sprintf("PC2 (%.2f%% variance)", var_explained[2])

# Dataframe for PCA plot
df <- data.frame(id=dat[,'mci'],
                 pc1=prcomp_results$x[,1], 
                 pc2=prcomp_results$x[,2],
                 gender=dat[,'GENDER'],
                 race=dat[,'RACE'])
# PCA plot
plt <- ggplot(df, aes(pc1, pc2, color=race, shape=gender)) +
    geom_point(stat="identity",size=3.5) +
    #geom_text(aes(label=id), angle=45, size=4, vjust=2) +
    xlab(xl) + ylab(yl) +
    ggtitle(sprintf("PCA: Individuals")) +
    theme(axis.ticks=element_blank(), axis.text.x=element_text(angle=-90))
plot(plt)
```

### Other visualizations

```{r}
# is there a relationship between race and variables? (just considered dominant
# categories)
dat_subset <- dat %>% 
    filter(RACE %in% c('White', 'Black or African American')) %>%
    select(-mci)
ggpairs(dat_subset, mapping=aes(colour=RACE, alpha=0.4))
```

Save combined table...

```{r}
write.csv(dat, file=sprintf('../data/combined/%s_%s.csv', analysis_name, analysis_version))
```

